"""
Scenario: Task Management (Write Operations)

Covers create, update, and delete operations for projects, tasks, and comments.
Each virtual user creates short-lived resources — tasks and comments — to keep
the database reasonably clean.

Endpoints covered:
  - POST /api/projects
  - POST /api/projects/:projectId/tasks
  - PUT /api/tasks/:id
  - PATCH /api/tasks/:id/assign
  - DELETE /api/tasks/:id
  - PUT /api/comments/:id
  - DELETE /api/comments/:id

Thresholds: POST/PUT/PATCH p95 < 1500 ms, DELETE p95 < 1000 ms.
"""

import random

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser

PROJECT_NAMES = [
    "Load Test Project Alpha",
    "Load Test Project Beta",
    "Load Test Project Gamma",
    "Perf Test Initiative",
    "Benchmark Sprint",
]

TASK_TITLES = [
    "Load test task - please ignore",
    "Benchmark: write throughput check",
    "Perf: create and delete cycle",
    "Test: update and assign flow",
]

TASK_UPDATES = [
    "Updated during load test run.",
    "Revised description — load test.",
    "Iteration 2 of perf test task.",
]

COMMENT_TEXTS = [
    "Load test comment — write path.",
    "Benchmark comment for PUT/DELETE.",
    "Perf test thread — ignore.",
    "Auto-generated by load test user.",
]

COMMENT_EDITS = [
    "Edited: load test complete.",
    "Updated during write scenario.",
    "Revised comment — benchmark run.",
]


class TaskManagementUser(TaskifyBaseUser):
    """Simulates users performing write operations on tasks and comments."""

    weight = 2

    # ------------------------------------------------------------------
    # Task lifecycle: create → update → assign → delete
    # ------------------------------------------------------------------

    @task(3)
    def create_and_update_task(self):
        """Create a task in a random project, update its title, then delete it."""
        if not self.projects:
            return

        project = random.choice(self.projects)
        project_id = project.get("id", project.get("_id"))

        # POST /api/projects/:projectId/tasks
        with self.client.post(
            f"/api/projects/{project_id}/tasks",
            json={"title": random.choice(TASK_TITLES)},
            name="POST /api/projects/:projectId/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1500:
                resp.failure(
                    f"create_task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1500ms"
                )
                return
            task_data = resp.json()

        task_id = task_data.get("id", task_data.get("_id"))

        # PUT /api/tasks/:id
        with self.client.put(
            f"/api/tasks/{task_id}",
            json={
                "title": random.choice(TASK_UPDATES),
                "description": "Updated by load test.",
            },
            name="PUT /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"update_task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1500:
                resp.failure(
                    f"update_task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1500ms"
                )

        # PATCH /api/tasks/:id/assign
        assigned_user_id = None
        if self.users:
            assigned_user_id = random.choice(self.users).get("id")

        with self.client.patch(
            f"/api/tasks/{task_id}/assign",
            json={"assigned_user_id": assigned_user_id},
            name="PATCH /api/tasks/:id/assign",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"assign_task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1500:
                resp.failure(
                    f"assign_task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1500ms"
                )

        # DELETE /api/tasks/:id
        with self.client.delete(
            f"/api/tasks/{task_id}",
            name="DELETE /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"delete_task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"delete_task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

    # ------------------------------------------------------------------
    # Comment lifecycle: create → edit → delete
    # ------------------------------------------------------------------

    @task(2)
    def create_and_manage_comment(self):
        """Post a comment on a task, edit it, then delete it."""
        if not self.projects:
            return

        project = random.choice(self.projects)
        project_id = project.get("id", project.get("_id"))

        # Fetch tasks for the project to find a stable task
        with self.client.get(
            f"/api/projects/{project_id}/tasks",
            name="[task-mgmt] GET /api/projects/:id/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"task_mgmt tasks: status {resp.status_code}")
                return
            tasks = resp.json()

        if not tasks:
            return

        chosen_task = random.choice(tasks)
        task_id = chosen_task.get("id", chosen_task.get("_id"))

        # POST comment (already covered by test_comments.py — name differs to avoid duplicate)
        with self.client.post(
            f"/api/tasks/{task_id}/comments",
            json={"content": random.choice(COMMENT_TEXTS)},
            headers={"X-User-Id": self.current_user_id},
            name="[task-mgmt] POST /api/tasks/:taskId/comments",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_comment: status {resp.status_code}")
                return
            comment_data = resp.json()

        comment_id = comment_data.get("id", comment_data.get("_id"))

        # PUT /api/comments/:id
        with self.client.put(
            f"/api/comments/{comment_id}",
            json={"content": random.choice(COMMENT_EDITS)},
            headers={"X-User-Id": self.current_user_id},
            name="PUT /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"edit_comment: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1500:
                resp.failure(
                    f"edit_comment: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1500ms"
                )

        # DELETE /api/comments/:id
        with self.client.delete(
            f"/api/comments/{comment_id}",
            headers={"X-User-Id": self.current_user_id},
            name="DELETE /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"delete_comment: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"delete_comment: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

    # ------------------------------------------------------------------
    # Project creation
    # ------------------------------------------------------------------

    @task(1)
    def create_project(self):
        """Create a new project to exercise the POST /api/projects endpoint."""
        # POST /api/projects
        with self.client.post(
            "/api/projects",
            json={
                "name": random.choice(PROJECT_NAMES),
                "description": "Auto-created by load test — safe to delete.",
            },
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_project: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1500:
                resp.failure(
                    f"create_project: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1500ms"
                )
