"""
Scenario: Project Creation

Simulates users creating new projects to measure write-load performance.
Threshold: POST p95 < 1000 ms.
"""

import random
from uuid import uuid4

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser


class ProjectCreationUser(TaskifyBaseUser):
    """User that creates projects under load."""

    weight = 2

    @task
    def create_project(self):
        """Create a project with a unique name."""
        project_name = f"Perf Project {uuid4().hex[:8]}"
        descriptions = [
            "Performance test project creation flow",
            "Synthetic project generated by Locust scenario",
            "Load test payload for project inserts",
        ]

        with self.client.post(
            "/api/projects",
            json={
                "name": project_name,
                "description": random.choice(descriptions),
            },
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_project: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"create_project: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
