"""
Scenario: Project Management

Simulates an admin user creating a new project.  Covers the single write
endpoint on the projects resource that is absent from all other scenarios.

Endpoint covered:
  POST /api/projects   — create a project

Threshold: POST p95 < 1000 ms.
"""

import random
import uuid

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser

PROJECT_NAME_PREFIXES = [
    "Alpha",
    "Beta",
    "Gamma",
    "Delta",
    "Epsilon",
    "Zeta",
    "Eta",
    "Theta",
]

PROJECT_DESCRIPTIONS = [
    "Performance test project — safe to delete.",
    "Auto-generated by load test.",
    None,
]


class ProjectManagementUser(TaskifyBaseUser):
    """User that creates new projects."""

    weight = 1

    @task
    def create_project(self):
        """Create a new project with a unique name."""
        name = f"{random.choice(PROJECT_NAME_PREFIXES)} Project {uuid.uuid4().hex[:6]}"
        description = random.choice(PROJECT_DESCRIPTIONS)

        payload: dict = {"name": name}
        if description:
            payload["description"] = description

        with self.client.post(
            "/api/projects",
            json=payload,
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_project: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"create_project: response time "
                    f"{resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
