"""
Scenario: Content Management

Simulates an admin/power user creating new projects and editing or removing
their own comments — covering the write-heavy mutation endpoints.
Thresholds: POST/PUT/DELETE p95 < 1000 ms.
"""

import random
import uuid

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser

PROJECT_PREFIXES = [
    "Initiative",
    "Workstream",
    "Campaign",
    "Milestone",
    "Program",
]

EDIT_COMMENT_TEXTS = [
    "Updated: see latest design doc for details.",
    "Revised estimate after team review.",
    "Clarified scope — only frontend changes needed.",
    "Corrected typo and added acceptance criteria.",
    "Added link to related ticket.",
]


class ContentManagementUser(TaskifyBaseUser):
    """User that creates projects and manages (edits/deletes) their own comments."""

    weight = 2

    @task(3)
    def create_project(self):
        """Create a new project, simulating an admin setting up a workstream."""
        name = f"{random.choice(PROJECT_PREFIXES)} {uuid.uuid4().hex[:6]}"
        with self.client.post(
            "/api/projects",
            json={"name": name, "description": "Auto-generated by load test"},
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"create_project: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"create_project: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

    @task(2)
    def edit_own_comment(self):
        """Post a comment then immediately edit it — exercises PUT /api/comments/:id."""
        if not self.projects:
            return

        project = random.choice(self.projects)
        project_id = project.get("id", project.get("_id"))

        # Fetch tasks
        with self.client.get(
            f"/api/projects/{project_id}/tasks",
            name="[content-mgmt] GET /api/projects/:id/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"edit_comment tasks: status {resp.status_code}")
                return
            tasks = resp.json()

        if not tasks:
            return

        task_id = random.choice(tasks).get("id")
        if not task_id:
            return

        # Post a comment
        comment_id = None
        with self.client.post(
            f"/api/tasks/{task_id}/comments",
            json={"content": "Draft comment — will edit shortly."},
            headers={"X-User-Id": self.current_user_id},
            name="[content-mgmt] POST /api/tasks/:taskId/comments",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"edit_comment post: status {resp.status_code}")
                return
            comment_id = resp.json().get("id")

        if not comment_id:
            return

        # Edit the comment
        with self.client.put(
            f"/api/comments/{comment_id}",
            json={"content": random.choice(EDIT_COMMENT_TEXTS)},
            headers={"X-User-Id": self.current_user_id},
            name="PUT /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"edit_comment put: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"edit_comment put: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

    @task(2)
    def delete_own_comment(self):
        """Post a comment then immediately delete it — exercises DELETE /api/comments/:id."""
        if not self.projects:
            return

        project = random.choice(self.projects)
        project_id = project.get("id", project.get("_id"))

        # Fetch tasks
        with self.client.get(
            f"/api/projects/{project_id}/tasks",
            name="[content-mgmt] GET /api/projects/:id/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"delete_comment tasks: status {resp.status_code}")
                return
            tasks = resp.json()

        if not tasks:
            return

        task_id = random.choice(tasks).get("id")
        if not task_id:
            return

        # Post a comment
        comment_id = None
        with self.client.post(
            f"/api/tasks/{task_id}/comments",
            json={"content": "Temporary comment — to be removed."},
            headers={"X-User-Id": self.current_user_id},
            name="[content-mgmt] POST /api/tasks/:taskId/comments",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"delete_comment post: status {resp.status_code}")
                return
            comment_id = resp.json().get("id")

        if not comment_id:
            return

        # Delete the comment
        with self.client.delete(
            f"/api/comments/{comment_id}",
            headers={"X-User-Id": self.current_user_id},
            name="DELETE /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"delete_comment delete: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"delete_comment delete: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
