"""
Scenario: Task Lifecycle

Simulates a project owner creating a project, adding a task to it, editing the
task, assigning it to a user and finally deleting it.  This exercises the full
write path of the projects/tasks API and cleans up after itself so repeated
runs stay deterministic.
Thresholds: GET p95 < 500 ms, POST/PUT/PATCH/DELETE p95 < 1000 ms.
"""

import random
import uuid

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser

WRITE_THRESHOLD_MS = 1000

TASK_TITLES = [
    "Load test task",
    "Refine acceptance criteria",
    "Investigate flaky integration test",
    "Update deployment runbook",
    "Wire up telemetry dashboard",
]


class TaskLifecycleUser(TaskifyBaseUser):
    """User that creates, edits, assigns and deletes work items."""

    weight = 2

    def _check(self, resp, label, expected=(200, 201)):
        """Fail the sample when status or latency is out of bounds."""
        if resp.status_code not in expected:
            resp.failure(f"{label}: status {resp.status_code}")
            return False
        if resp.elapsed.total_seconds() * 1000 > WRITE_THRESHOLD_MS:
            resp.failure(
                f"{label}: response time {resp.elapsed.total_seconds()*1000:.0f}ms "
                f"> {WRITE_THRESHOLD_MS}ms"
            )
            return False
        return True

    @task
    def task_lifecycle(self):
        """Create a project + task, update it, assign it, then delete it."""
        run_id = uuid.uuid4().hex[:8]

        # Create a scratch project so the scenario never mutates seed data
        with self.client.post(
            "/api/projects",
            json={
                "name": f"Perf project {run_id}",
                "description": "Created by the task lifecycle performance scenario",
            },
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if not self._check(resp, "task_lifecycle create project", expected=(201,)):
                return
            project_id = resp.json().get("id")

        if project_id is None:
            return

        # Create a task inside the scratch project
        with self.client.post(
            f"/api/projects/{project_id}/tasks",
            json={
                "title": f"{random.choice(TASK_TITLES)} {run_id}",
                "description": "Generated by the task lifecycle performance scenario",
            },
            name="POST /api/projects/:projectId/tasks",
            catch_response=True,
        ) as resp:
            if not self._check(resp, "task_lifecycle create task", expected=(201,)):
                return
            task_id = resp.json().get("id")

        if task_id is None:
            return

        # Edit the task title/description
        with self.client.put(
            f"/api/tasks/{task_id}",
            json={
                "title": f"Updated {run_id}",
                "description": "Updated by the task lifecycle performance scenario",
            },
            name="PUT /api/tasks/:id",
            catch_response=True,
        ) as resp:
            self._check(resp, "task_lifecycle update task", expected=(200,))

        # Assign the task to the simulated user
        assigned_user_id = None
        if self.users:
            assigned_user_id = random.choice(self.users).get("id")

        with self.client.patch(
            f"/api/tasks/{task_id}/assign",
            json={"assigned_user_id": assigned_user_id},
            name="PATCH /api/tasks/:id/assign",
            catch_response=True,
        ) as resp:
            self._check(resp, "task_lifecycle assign task", expected=(200,))

        # Clean up the task so the dataset does not grow unbounded
        with self.client.delete(
            f"/api/tasks/{task_id}",
            name="DELETE /api/tasks/:id",
            catch_response=True,
        ) as resp:
            self._check(resp, "task_lifecycle delete task", expected=(200,))
