"""
Scenario: Task Lifecycle Management

Simulates creating a project and task, updating assignment and content,
moderating comments, and deleting created entities.
Thresholds: POST/PATCH/PUT/DELETE p95 < 1000 ms.
"""

import random
import uuid

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser


class TaskLifecycleUser(TaskifyBaseUser):
    """User that exercises high-risk task and comment write endpoints."""

    weight = 2

    @task
    def task_lifecycle(self):
        """Create and mutate project/task/comment entities end-to-end."""
        if not self.current_user_id:
            return

        headers = {"X-User-Id": self.current_user_id}
        assigned_user_id = None
        if self.users:
            random_user = random.choice(self.users)
            assigned_user_id = random_user.get("id", random_user.get("_id"))

        project_id = None
        task_id = None
        comment_id = None

        # Create project
        with self.client.post(
            "/api/projects",
            json={
                "name": f"Perf Project {uuid.uuid4().hex[:8]}",
                "description": "Generated by Locust performance scenario",
            },
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle create project: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create project: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            project = resp.json()
            project_id = project.get("id", project.get("_id"))

        if not project_id:
            return

        # Create task
        with self.client.post(
            f"/api/projects/{project_id}/tasks",
            json={
                "title": f"Perf Task {uuid.uuid4().hex[:6]}",
                "description": "Task lifecycle baseline",
                "assigned_user_id": assigned_user_id,
            },
            headers=headers,
            name="POST /api/projects/:projectId/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle create task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            task = resp.json()
            task_id = task.get("id", task.get("_id"))

        if not task_id:
            return

        # Update task content
        with self.client.put(
            f"/api/tasks/{task_id}",
            json={
                "title": f"Perf Task Updated {uuid.uuid4().hex[:6]}",
                "description": "Updated during lifecycle scenario",
            },
            headers=headers,
            name="PUT /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle update task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle update task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return

        # Assign/unassign task
        with self.client.patch(
            f"/api/tasks/{task_id}/assign",
            json={"assigned_user_id": assigned_user_id},
            headers=headers,
            name="PATCH /api/tasks/:id/assign",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle assign task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle assign task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return

        # Create comment
        with self.client.post(
            f"/api/tasks/{task_id}/comments",
            json={"content": "Task lifecycle comment", "user_id": self.current_user_id},
            headers=headers,
            name="[lifecycle] POST /api/tasks/:taskId/comments",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle create comment: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create comment: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            comment = resp.json()
            comment_id = comment.get("id", comment.get("_id"))

        if not comment_id:
            return

        # Update comment
        with self.client.put(
            f"/api/comments/{comment_id}",
            json={"content": f"Updated lifecycle comment {uuid.uuid4().hex[:6]}"},
            headers=headers,
            name="PUT /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle update comment: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle update comment: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return

        # Delete comment
        with self.client.delete(
            f"/api/comments/{comment_id}",
            headers=headers,
            name="DELETE /api/comments/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle delete comment: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle delete comment: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return

        # Delete task
        with self.client.delete(
            f"/api/tasks/{task_id}",
            headers=headers,
            name="DELETE /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code < 200 or resp.status_code >= 300:
                resp.failure(f"task_lifecycle delete task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle delete task: response time {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
