"""
Scenario: Task Lifecycle

Simulates a user creating a project, adding a task, editing the task,
assigning a user, and finally deleting the task.  This covers the full
write path for projects and tasks.

Covered endpoints:
  POST /api/projects
  POST /api/projects/:projectId/tasks
  PUT  /api/tasks/:id
  PATCH /api/tasks/:id/assign
  DELETE /api/tasks/:id

Thresholds: POST/PUT/PATCH/DELETE p95 < 1000 ms.
"""

import random
import uuid

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser

TASK_TITLES = [
    "Implement login flow",
    "Write API documentation",
    "Fix CSS regression",
    "Add unit tests",
    "Review pull request",
    "Update dependencies",
    "Refactor auth module",
    "Set up CI pipeline",
]

TASK_DESCRIPTIONS = [
    "This needs careful attention to detail.",
    "Depends on the design spec.",
    "Blocked by upstream team.",
    "Low priority, carry over from last sprint.",
    "",
]

PROJECT_NAMES = [
    "Perf Test Project",
    "Load Test Sandbox",
    "Temporary Benchmark",
]


class TaskLifecycleUser(TaskifyBaseUser):
    """User that exercises the full project + task write lifecycle."""

    weight = 3

    @task
    def task_lifecycle(self):
        """Create a project, add a task, edit it, assign a user, then delete it."""
        # ── Step 1: Create a project ─────────────────────────────────────
        project_name = f"{random.choice(PROJECT_NAMES)} {uuid.uuid4().hex[:6]}"
        with self.client.post(
            "/api/projects",
            json={"name": project_name, "description": "Auto-generated by load test"},
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"task_lifecycle create_project: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create_project: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            project = resp.json()

        project_id = project.get("id", project.get("_id"))

        # ── Step 2: Add a task ────────────────────────────────────────────
        title = random.choice(TASK_TITLES)
        with self.client.post(
            f"/api/projects/{project_id}/tasks",
            json={
                "title": title,
                "description": random.choice(TASK_DESCRIPTIONS),
            },
            name="POST /api/projects/:projectId/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"task_lifecycle create_task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create_task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            created_task = resp.json()

        task_id = created_task.get("id", created_task.get("_id"))

        # ── Step 3: Edit the task ─────────────────────────────────────────
        updated_title = f"{title} (updated)"
        with self.client.put(
            f"/api/tasks/{task_id}",
            json={"title": updated_title, "description": "Updated by load test"},
            name="PUT /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"task_lifecycle update_task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle update_task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

        # ── Step 4: Assign a user ─────────────────────────────────────────
        if self.users:
            assignee = random.choice(self.users)
            assignee_id = str(assignee.get("id", assignee.get("_id")))
            with self.client.patch(
                f"/api/tasks/{task_id}/assign",
                json={"assigned_user_id": assignee_id},
                name="PATCH /api/tasks/:id/assign",
                catch_response=True,
            ) as resp:
                if resp.status_code != 200:
                    resp.failure(f"task_lifecycle assign_task: status {resp.status_code}")
                elif resp.elapsed.total_seconds() * 1000 > 1000:
                    resp.failure(
                        f"task_lifecycle assign_task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                    )

        # ── Step 5: Delete the task ───────────────────────────────────────
        with self.client.delete(
            f"/api/tasks/{task_id}",
            name="DELETE /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"task_lifecycle delete_task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle delete_task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
