"""
Scenario: Task CRUD Lifecycle

Simulates a developer creating a project, adding tasks, editing and
reassigning them, then cleaning up by deleting the tasks and the project.

Covered endpoints:
  POST   /api/projects
  POST   /api/projects/:projectId/tasks
  PUT    /api/tasks/:id
  PATCH  /api/tasks/:id/assign
  DELETE /api/tasks/:id

Thresholds: POST/PUT/PATCH/DELETE p95 < 1000 ms.
"""

import random

from locust import task

try:
    from .base import TaskifyBaseUser
except ImportError:
    from base import TaskifyBaseUser


PROJECT_NAMES = [
    "Perf Test Project Alpha",
    "Perf Test Project Beta",
    "Perf Test Project Gamma",
    "Perf Test Project Delta",
]

TASK_TITLES = [
    "Implement login flow",
    "Write unit tests",
    "Fix navbar styling",
    "Deploy to staging",
    "Update API docs",
    "Refactor database layer",
]

TASK_DESCRIPTIONS = [
    "This task was generated by a performance test.",
    "Automated load-test task — safe to delete.",
    "Created during perf run.",
    None,
]


class TaskCrudUser(TaskifyBaseUser):
    """User that exercises the full task CRUD lifecycle."""

    weight = 2

    @task
    def task_lifecycle(self):
        """Create a project, add a task, edit/reassign it, then delete everything."""
        # ------------------------------------------------------------------
        # Step 1: Create a project
        # ------------------------------------------------------------------
        project_name = random.choice(PROJECT_NAMES) + f" {random.randint(1000, 9999)}"
        with self.client.post(
            "/api/projects",
            json={"name": project_name, "description": "Perf test project"},
            name="POST /api/projects",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"task_lifecycle create project: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create project: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            project = resp.json()

        project_id = project.get("id", project.get("_id"))
        if not project_id:
            return

        # ------------------------------------------------------------------
        # Step 2: Create a task inside that project
        # ------------------------------------------------------------------
        task_title = random.choice(TASK_TITLES)
        task_desc = random.choice(TASK_DESCRIPTIONS)
        with self.client.post(
            f"/api/projects/{project_id}/tasks",
            json={"title": task_title, "description": task_desc},
            name="POST /api/projects/:projectId/tasks",
            catch_response=True,
        ) as resp:
            if resp.status_code != 201:
                resp.failure(f"task_lifecycle create task: status {resp.status_code}")
                return
            if resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle create task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
                return
            created_task = resp.json()

        task_id = created_task.get("id", created_task.get("_id"))
        if not task_id:
            return

        # ------------------------------------------------------------------
        # Step 3: Update the task title and description
        # ------------------------------------------------------------------
        with self.client.put(
            f"/api/tasks/{task_id}",
            json={
                "title": task_title + " (updated)",
                "description": "Updated by performance test",
            },
            name="PUT /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code not in (200, 201):
                resp.failure(f"task_lifecycle update task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle update task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

        # ------------------------------------------------------------------
        # Step 4: Assign a random user to the task
        # ------------------------------------------------------------------
        assigned_user_id = None
        if self.users:
            user = random.choice(self.users)
            assigned_user_id = str(user.get("id", user.get("_id")))

        with self.client.patch(
            f"/api/tasks/{task_id}/assign",
            json={"assigned_user_id": assigned_user_id},
            name="PATCH /api/tasks/:id/assign",
            catch_response=True,
        ) as resp:
            if resp.status_code not in (200, 201):
                resp.failure(f"task_lifecycle assign task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle assign task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )

        # ------------------------------------------------------------------
        # Step 5: Delete the task (clean-up)
        # ------------------------------------------------------------------
        with self.client.delete(
            f"/api/tasks/{task_id}",
            name="DELETE /api/tasks/:id",
            catch_response=True,
        ) as resp:
            if resp.status_code not in (200, 204):
                resp.failure(f"task_lifecycle delete task: status {resp.status_code}")
            elif resp.elapsed.total_seconds() * 1000 > 1000:
                resp.failure(
                    f"task_lifecycle delete task: {resp.elapsed.total_seconds()*1000:.0f}ms > 1000ms"
                )
